---
- hosts: dev
  become: true
  tasks:
    - dnf:
        name:
          - httpd
        state: present
    - service: name=httpd state=started enabled=yes
    - raw: "echo CopyRight by MSA 2023 all right reserved | sudo tee /var/www/html/index.html"
